# Generated by Django 4.0.4 on 2022-05-11 10:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Subject')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Test', max_length=250, verbose_name='Title')),
                ('description', models.TextField()),
                ('time_interval', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('time_between_attempts', models.DurationField(default=datetime.timedelta(days=30))),
                ('image', models.ImageField(upload_to='uploads/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillful.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TestTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='yesterday', max_length=250)),
                ('public', models.BooleanField()),
                ('result', models.IntegerField()),
                ('canceled', models.BooleanField()),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillful.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Taken Tests',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('is_multiple_choice', models.BooleanField()),
                ('type', models.CharField(max_length=250)),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skillful.subject')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillful.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillful.question')),
            ],
        ),
    ]
