# Generated by Django 4.0.4 on 2022-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillful', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='difficulty_level',
            field=models.CharField(choices=[('1', 'easy'), ('2', 'medium'), ('3', 'hard'), ('4', 'expert')], default='1', max_length=1),
        ),
    ]
