# Generated by Django 4.0.4 on 2022-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillful', '0002_test_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
