# Generated by Django 4.0.4 on 2022-05-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillful', '0005_rename_programming_language_question_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
