# Generated by Django 4.0.4 on 2022-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillful', '0006_remove_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Title of the Test', max_length=250, verbose_name='Title'),
        ),
    ]
