# Generated by Django 4.0.4 on 2022-05-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillful', '0008_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
    ]
